# Generated by Django 2.2.4 on 2019-12-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petter', '0002_auto_20191205_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='coat',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='group',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='heart_worm_treated',
        ),
    ]
