# Generated by Django 2.2.4 on 2019-12-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petter', '0003_auto_20191207_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='postcode_range',
        ),
        migrations.AddField(
            model_name='pets',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('rabbit', 'Rabbit'), ('bird', 'Bird')], default='', max_length=10),
        ),
    ]
